### PR TITLE
:card_file_box:[597] added ordering for each field

### LINKED ISSUE #597: Add ordering on all models

### PR DESCRIPTION
**Pull request by bart-maykin**
Fixes #597

_______

**Changes**

Added ordering for all model fields
Updated tests that broke because of ordering

### CODE REVIEW

**Comment by alextreme** [comment]
Bij deze in orde, explicit (ordering) is better than implicit (ordering)

**Review by alextreme — APPROVED** [review]

**Comment by alextreme** [comment]
Does require some wrangling of migrations (didn't notice this PR was so old):

CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0021_auto_20220503_1806, 0025_alter_bevoegdeorganisatie_naam in organisaties; 0030_auto_20220503_1922, 0032_alter_product_options in producten; 0029_auto_20220503_1747, 0032_data_migration_set_is_default_catalogus_true in core; 0003_alter_token_options, 0003_tokenauthorization in api).
To fix them run 'python manage.py makemigrations --merge'

**Review by alextreme — CHANGES_REQUESTED** [review]
migration conflicts

**Comment by joeribekker** [comment]
Deze moet nog open blijven staan. Deze is al half gedaan waar nodig.

**Pull request closed without merging**
