### PR TITLE
Flags and group filters

### LINKED ISSUE #201: Als redacteur wil ik kunnen kiezen tussen de doelgroepen burger- of ondernemer
Only do after #217 

**Tasks**

* [x] Replace language "name" with flag. Show grey if language present, show colored when datumCheck is filled.
* [x] Use Dutch and British flags for languages
* [x] Add doelgroep to detail/edit page as a field
* [x] Add doelgroep to list item, after the flags
* [x] Add filter (checkboxes) for: "Voor burgers" "Voor bedrijven" which filter on doelgroep.

*Verduidelijkt met Frank*

**Original ticket**

opdat ik mijn tekst kan richten op de juiste doelgroep.

De invoervoorziening weet of een of een product een burger en/of ondernemerproduct is door het inlezen van de UPL (zie #116)

De invoervoorziening toont aan de redacteur nu niet de doelgroep. Nog te bepalen waar de doelgroep getoond gaat worden. Bijvoorbeeld:
- als filter in de productenlijst. Een redacteur kan dan alle burger, ondernemer of alle burger én ondernemer producten zien.
- bij de generieke tekst
- in de producttitel
   - onroerende zaakbelasting (ozb) voor **burgers**
   - onroerende zaakbelasting (ozb) voor **ondernemers**

### PR DESCRIPTION
**Pull request by dariomory**
Fixes #201

_______

**Changes**

- Fix bug with missing reference translation
- Add and integrate flag-icon-css
- Create and implement `Language` type 
- Allow editing product target groups
- Add target group filter

flags

doelgroep

filters

### CODE REVIEW

**Review by joeribekker — CHANGES_REQUESTED** [review]
Small stuff.

**Comment by joeribekker** [comment]
I also noticed generic info seems missing from the detail page for english (or probably uncheckedlanguages)?

**Comment by dariomory** [comment]
> I also noticed generic info seems missing from the detail page for english (or probably uncheckedlanguages)?

Hmm.. This is (hopefully) happening due to a missing localized generic translation.

**Comment by joeribekker** [comment]
I'm sorry Dario. I see I didn't spec the ticket well enough.

We assume the localized version is ALWAYS present (because generated automatically). Anyway, I think this will be refactored a bit with #24.

**Review by joeribekker — APPROVED** [review]

**Pull request merged**
