### PR TITLE
:sparkles: #412 - Als redacteur wil ik een duidelijk overzicht van al…

### LINKED ISSUE #412: Als redacteur wil ik een duidelijk overzicht van alle producten waarin ik een filter kan toepassen
**Tasks**

* [x] Refactor naar lijst/kolommen: naam, doelgroep(en), status, laatst gewijzigd/gewijzigd door (vervangt bovenstaande 2 punten)

Out of scope:

* [x] Filters moeten andere items "grijs" maken (muten)
* [x] Lege categorieen weglaten
* [ ] Lijst volledige schermbreedte geven?

Inschatting: 1 week werk

### LINKED ISSUE #428: Eerste pagina (detailpagina) overslaan, meteen naar aanpassen
**Tasks**

* [x] Link product from list view top edit page @svenvandescheur 
* [x] Remove obsolete code for detail page @dariomory

### PR DESCRIPTION
**Pull request by svenvandescheur**
…le producten waarin ik een filter kan toepassen.

Fixes #412
Fixes #428

_______

**Changes**

Replace CatalogListView contents with a grid layout.

Peek 2022-03-09 15-13

### CODE REVIEW

**Comment by svenvandescheur** [comment]
@dariomory can you look at the tests?

**Review by dariomory — CHANGES_REQUESTED** [review]
Good :) Just some fronted CI issues left.

I've explicitly skipped two tests (regarding displaying the reference catalog) needs to be discussed with @joeribekker.

**Comment by svenvandescheur** [comment]
I've had a look at the build failed. This is due to webpack/bash not being able to locate the site_packages in env (which unfortunatly is required) to build static sources (long story short: sdg imports fonts/stylesheets from django-rijkshuisstijl package).

In ci no environment seems to be created and no (virtual) env is found, therefore:

collect.sh failes.
webpack fails.

Fixing this would require some changes on the ci scripts/image. I think the most practical solution would be to change the build image to create a virtual environment (which should be picked up by the frontend build).

**Comment by dariomory** [comment]
The venv situation is fixed. Some missing woff2 files are preventing static collection, @svenvandescheur is on it.

**Review by dariomory — APPROVED** [review]

**Pull request merged**
